#! /usr/bin/perl
while (<>) {
  next if /^\|/ || /^\s*$/;
  if (/^\s*include\s+(\S+)\s*$/) {
    print STDERR "$1\n";
    print `perl $0 <$1`;
  } else {
    s/\r?\n//s;
    s/(["\\])/\\$1/g;
    print "  \"$_\\n\"\n";
  }
}

